

INSERT INTO USER_ACCOUNT(UID,USER_ROLE,EMAIL,USER_PASSWORD,FIRST_NAME,LAST_NAME) values (nextval('USER_ACCOUNT_SEQ'),'ADMINISTRATOR','admin@master','parola12345','Aadministrator','');
INSERT INTO FOOD_PRICES(foodpriceid,breakfast,dinner,lunch) values (1,25,35,10);
INSERT INTO ROOM(ROOMID, AIRCONDITIONER, DESCRIPTION, HYDROMASSAGETUB, INTERNET,PETS, PHONE, PRICE, ROOMNUMBER, ROOMTYPE, ROOMVIEW, SAFE, SMOKING,TEACOFFEE, VIRTUALROOM, DELETED)VALUES (nextval('ROOM_SEQ'),FALSE, 'If you want accommodation in Constanta, please choose Hotel Blue Sea which has modern furnished and equipped according to the standards of 4 stars, they satisfy even the most discerning guest. Room is modern furnished, spacious and clean. Has full bathroom is equipped with television, cable television, ventilation and minibar. For double room can supplement choice with another bed.',TRUE, TRUE, FALSE, TRUE, 100, 1, 'single', TRUE, FALSE,FALSE, FALSE, FALSE, FALSE);
INSERT INTO ROOM(ROOMID, AIRCONDITIONER, DESCRIPTION, HYDROMASSAGETUB, INTERNET,PETS, PHONE, PRICE, ROOMNUMBER, ROOMTYPE, ROOMVIEW, SAFE, SMOKING,TEACOFFEE, VIRTUALROOM, DELETED)VALUES (nextval('ROOM_SEQ'),FALSE, 'If you want accommodation in Constanta, please choose Hotel Blue Sea which has modern furnished and equipped according to the standards of 4 stars, they satisfy even the most discerning guest. Room is modern furnished, spacious and clean. Has full bathroom is equipped with television, cable television, ventilation and minibar. For double room can supplement choice with another bed.',TRUE, TRUE, FALSE, TRUE, 100, 2, 'single', TRUE, FALSE,FALSE, FALSE, FALSE, FALSE);
INSERT INTO ROOM(ROOMID, AIRCONDITIONER, DESCRIPTION, HYDROMASSAGETUB, INTERNET,PETS, PHONE, PRICE, ROOMNUMBER, ROOMTYPE, ROOMVIEW, SAFE, SMOKING,TEACOFFEE, VIRTUALROOM, DELETED)VALUES (nextval('ROOM_SEQ'),FALSE, 'If you want accommodation in Constanta, please choose Hotel Blue Sea which has modern furnished and equipped according to the standards of 4 stars, they satisfy even the most discerning guest. Room is modern furnished, spacious and clean. Has full bathroom is equipped with television, cable television, ventilation and minibar. For double room can supplement choice with another bed.',TRUE, TRUE, FALSE, TRUE, 100, 3, 'single', TRUE, FALSE,FALSE, FALSE, FALSE, FALSE);
INSERT INTO ROOM(ROOMID, AIRCONDITIONER, DESCRIPTION, HYDROMASSAGETUB, INTERNET,PETS, PHONE, PRICE, ROOMNUMBER, ROOMTYPE, ROOMVIEW, SAFE, SMOKING,TEACOFFEE, VIRTUALROOM, DELETED)VALUES (nextval('ROOM_SEQ'),FALSE, 'If you want accommodation in Constanta, please choose Hotel Blue Sea which has modern furnished and equipped according to the standards of 4 stars, they satisfy even the most discerning guest. Room is modern furnished, spacious and clean. Has full bathroom is equipped with television, cable television, ventilation and minibar. For double room can supplement choice with another bed.',TRUE, TRUE, FALSE, TRUE, 100, 4, 'single', TRUE, FALSE,FALSE, FALSE, FALSE, FALSE);
INSERT INTO ROOM(ROOMID, AIRCONDITIONER, DESCRIPTION, HYDROMASSAGETUB, INTERNET,PETS, PHONE, PRICE, ROOMNUMBER, ROOMTYPE, ROOMVIEW, SAFE, SMOKING,TEACOFFEE, VIRTUALROOM, DELETED)VALUES (nextval('ROOM_SEQ'),FALSE, 'If you want accommodation in Constanta, please choose Hotel Blue Sea which has modern furnished and equipped according to the standards of 4 stars, they satisfy even the most discerning guest. Room is modern furnished, spacious and clean. Has full bathroom is equipped with television, cable television, ventilation and minibar. For double room can supplement choice with another bed.',TRUE, TRUE, FALSE, TRUE, 100, 5, 'single', TRUE, FALSE,FALSE, FALSE, FALSE, FALSE);
INSERT INTO ROOM(ROOMID, AIRCONDITIONER, DESCRIPTION, HYDROMASSAGETUB, INTERNET,PETS, PHONE, PRICE, ROOMNUMBER, ROOMTYPE, ROOMVIEW, SAFE, SMOKING,TEACOFFEE, VIRTUALROOM, DELETED)VALUES (nextval('ROOM_SEQ'),FALSE, 'If you want accommodation in Constanta, please choose Hotel Blue Sea which has modern furnished and equipped according to the standards of 4 stars, they satisfy even the most discerning guest. Room is modern furnished, spacious and clean. Has full bathroom is equipped with television, cable television, ventilation and minibar. For double room can supplement choice with another bed.',TRUE, TRUE, FALSE, TRUE, 100, 6, 'single', TRUE, FALSE,FALSE, FALSE, FALSE, FALSE);
